### ISSUE TITLE
[Feature Request] Auto update for css

### ISSUE THREAD

**Issue by ShakeSphereStuff** [Ruud14/Page-Manipulator#47]
When refreshing a page, I have to manually toggle the “manipulate css” button in order for it to make changes:
Here’s what I’m using:
- uBlockOrigin
- Dark Reader
- Cold Turkey Blocker
- Qwant Search Redirect

Here was the code I wrote:

```css
.Kiog.kNVGM.nvpSA.qwdi.bmjsw {
    grid-template-columns: repeat(1,1fr)
}
```

and the website used: [Website](https://abcnews.go.com/US/story?id=1809368&page=1)

If this cannot be achieved, please respond in the issue bellow I would love to know

Great seeing an open source dev creating a great product
